name: pet_tracker
description: "A new project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  cupertino_icons: ^1.0.8
  dio: ^5.7.0
  firebase_core: ^3.6.0
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.2.1
  flutter_map: ^7.0.2
  flutter_riverpod: ^2.6.1
  flutter_svg: ^2.0.10+1
  formz: ^0.8.0
  go_router: ^14.3.0
  latlong2: ^0.9.1
  shared_preferences: ^2.3.2
  web_socket_channel: ^2.4.0

dev_dependencies:
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - .env
